version: "3.9"

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=mov_us
      - POSTGRES_PASSWORD=mov_secret
    ports:
      - "5432:5432"
    
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  pg-admin:
    image: dpage/pgadmin4:8.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    

volumes:
  postgres-data: